# Generated by Django 6.0.3 on 2026-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_season',
            field=models.CharField(choices=[('summer', 'Summer'), ('rainy', 'Rainy'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='summer', max_length=16),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_travel_style',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_travel_style',
            field=models.ManyToManyField(to='users.travelstyle'),
        ),
    ]
