# Generated by Django 6.0.3 on 2026-04-05 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_travelstyle_alter_userprofile_preferred_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='budget_preference',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_season',
            field=models.CharField(choices=[('summer', 'Summer'), ('rainy', 'Rainy'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='summer', max_length=20),
        ),
    ]
