# Generated by Django 6.0.3 on 2026-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('duration', models.IntegerField()),
                ('culture', models.IntegerField(default=0)),
                ('adventure', models.IntegerField(default=0)),
                ('wildlife', models.IntegerField(default=0)),
                ('sightseeing', models.IntegerField(default=0)),
                ('history', models.IntegerField(default=0)),
            ],
        ),
    ]
