# Generated by Django 6.0.3 on 2026-03-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_travelpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='province',
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.destination'),
        ),
    ]
