# Generated by Django 6.0.3 on 2026-04-01 16:29

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import recommendation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_remove_travelpackage_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('description', models.TextField(default='')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='destination',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='end_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_packages', to='recommendation.destination'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/', validators=[recommendation.models.validate_image]),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='number_of_travelers',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='package_type',
            field=models.CharField(choices=[('tour', 'Tour'), ('hiking', 'Hiking'), ('sightseeing', 'Sightseeing'), ('adventure', 'Adventure')], default='tour', max_length=20),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='start_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_packages', to='recommendation.destination'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='transport_mode',
            field=models.CharField(choices=[('car', 'Car'), ('jeep', 'Jeep'), ('bus', 'Bus'), ('flight', 'Flight'), ('bike', 'Bike')], default='bus', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='budget',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('pName'), django.db.models.functions.text.Lower('province'), name='unique_destination_case_insensitive'),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.destination'),
        ),
        migrations.AddField(
            model_name='packageitinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='recommendation.travelpackage'),
        ),
        migrations.AlterUniqueTogether(
            name='packageitinerary',
            unique_together={('package', 'day_number', 'destination')},
        ),
    ]
